name: Pipeline AQI horaire

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

concurrency:
  group: Pipeline AQI
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du repo.
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: pip install -r config/requirements.txt

      - name: Extraire les données AQI
        run: python -m dags.run_extract
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

      - name: Nettoyer et transformer les données
        run: python -m transform.build_clean

      - name: Construire et charger le warehouse
        run: python -m warehouse.build_warehouse
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Committer les nouveaux fichiers
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add raw/
          git add clean/
          git diff --staged --quiet || git commit -m "Data AQI brute & clean $(date -u +'%Y-%m-%dT%H:%M')"
          git push
